### ISSUE TITLE
Project setup instructions

### ISSUE THREAD

**Issue by saikumarb23** [rrathi0705/fooder#2]
Hello,

Could you please provide project setup instructions such as software's to use ? Also, which file contains SQL server connection details ?

**Comment by rrathi0705** [comment]
If you haven't downloaded Xampp or any web server then download it from "https://www.apachefriends.org/download.html". Then open the **xampp/ wampp** or any other web server and start **apache** and **MySQL**. Then go to the web browser and type "http://localhost/fooder/index.php" in the URL. You would be able to see the main page.
For database connectivity type "http://localhost/phpmyadmin/" and then import **database.sql** file. You would see a food database created.
If you find any difficulty let me know and sorry for the late reply.
Thanking you
